name: Build & Test against catalogs
on: [push, pull_request,repository_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

env:
  BASE_BRANCH: ${{ github.base_ref || (endsWith(github.ref, '_feature') && 'feature' || 'main') }}

jobs:
  build_iceberg:
    name: Build
    runs-on: ubuntu-latest
    env:
      VCPKG_TARGET_TRIPLET: 'x64-linux-release'
      GEN: ninja
      VCPKG_FEATURE_FLAGS: "-binarycaching"
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      PIP_BREAK_SYSTEM_PACKAGES: 1

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.1
        with:
          vcpkgGitCommitId: 84bab45d415d22042bd0b9081aea57f362da3f35

      - name: Install Ninja
        shell: bash
        run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build

      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ github.job }}
          save: ${{ github.ref == 'refs/heads/main' || github.repository != 'duckdb/duckdb' }}

      - name: Build extension
        env:
          GEN: ninja
          STATIC_LIBCPP: 1
          ENABLE_EXTENSION_AUTOLOADING: 1
          ENABLE_EXTENSION_AUTOINSTALL: 1
        run: |
          make release

      - name: Upload DuckDB-Iceberg release folder
        uses: actions/upload-artifact@v4
        with:
          name: duckdb-iceberg
          path: build/release/
          retention-days: 3

  test-fixture:
    name: Test against fixture catalog
    needs: build_iceberg
    uses: ./.github/workflows/test-fixture-catalog.yml
    with:
      artifact-name: duckdb-iceberg

  test-nessie:
    name: Test against Nessie Catalog
    needs: build_iceberg
    uses: ./.github/workflows/test-nessie-catalog.yml
    with:
      artifact-name: duckdb-iceberg

#  test-polaris:
#    name: Test against Polaris Catalog
#    needs: build_iceberg
#    uses: ./.github/workflows/test-polaris-catalog.yml
#    with:
#      artifact-name: duckdb-iceberg